# Imagem base do Git
FROM alpine:3.12

# Instalar o Git
RUN apk add --no-cache git

# Definir o diretório de trabalho
WORKDIR /var/www/html

# Clonar o repositório e os submódulos
COPY . .

# Executar comandos para inicializar e atualizar submódulos
RUN git submodule init && git submodule update
