version: '3.8'

services:
  submodule:
    build:
      context: .
      dockerfile: Dockerfile.submodule
    container_name: submodule
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    command: >
      sh -c "[ -d .git/modules ] || (git submodule init && git submodule update)"

  symfony:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: symfony
    volumes:
      - ./backend:/var/www/html
    working_dir: /var/www/html
    depends_on:
      - db
      - submodule
    networks:
      - app-network
    command: >
      sh -c "composer install & php bin/console doctrine:migrations:migrate --no-interaction && php -S 0.0.0.0:8080 -t public"
    ports:
      - "8080:8080"

  nextjs:
    image: node:18
    container_name: nextjs
    volumes:
      - ./frontend:/usr/src/app
    working_dir: /usr/src/app
    depends_on:
      - symfony
    networks:
      - app-network
    command: >
      sh -c "npm install && npm run dev"
    ports:
      - "3000:3000"

  db:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: onesign
      MYSQL_USER: onesign
      MYSQL_PASSWORD: onesign
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
